<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '475c7c176b84fe5b379d00bd33754c5b',
  'DATABASE_URL' => 'mysql://razvan:razvan123@https://eu-west-3.console.aws.amazon.com/rds/home?region=eu-west-3',
  'CORS_ALLOW_ORIGIN' => '^https?://localhost(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => 'be4056287f96514543fdaeb9889ce065',
);
